# Generated by Django 5.0.4 on 2026-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_invoicetosspayments_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicetosspayments',
            name='confirm_response',
            field=models.TextField(blank=True, null=True, verbose_name='Confirm response field'),
        ),
    ]
