# Generated by Django 5.0.4 on 2026-05-07 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_invoicetosspayments_confirm_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetosspayments',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='invoicetosspayments',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='invoicetosspayments',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='invoicetosspayments',
            name='manager_link',
        ),
    ]
