# Generated by Django 5.0.4 on 2026-05-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_remove_invoicetosspayments_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicetosspayments',
            options={'verbose_name': 'Счёт на оплату', 'verbose_name_plural': 'Счёта на оплату'},
        ),
    ]
