# Generated by Django 5.0.4 on 2026-05-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_invoicetosspayments_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicetosspayments',
            name='payment_type',
        ),
    ]
