# Generated by Django 5.0.4 on 2026-09-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_siteorder_business_ru_document_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteorder',
            name='business_ru_order_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='№ заказа покупателя'),
        ),
        migrations.AlterField(
            model_name='siteorder',
            name='business_ru_payment_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='№ входящей оплаты'),
        ),
        migrations.AlterField(
            model_name='siteorder',
            name='business_ru_reservation_number',
            field=models.CharField(blank=True, max_length=32, verbose_name='№ резерва'),
        ),
    ]
