# Generated by Django 5.0.4 on 2026-09-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_checkoutsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsettings',
            name='paypal_enabled',
            field=models.BooleanField(default=False, help_text='Ключи PayPal остаются в .env. Этот флаг только показывает оплату на витрине.', verbose_name='PayPal на сайте'),
        ),
        migrations.AlterField(
            model_name='checkoutsettings',
            name='telegram_enabled',
            field=models.BooleanField(default=False, help_text='Консультация в подвале сайта работает независимо от этого флага.', verbose_name='Заказ в Telegram'),
        ),
    ]
