# Generated by Django 5.0.4 on 2026-10-01 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0043_tbank_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteorder',
            name='display_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Показано клиенту'),
        ),
        migrations.AddField(
            model_name='siteorder',
            name='display_currency',
            field=models.CharField(blank=True, max_length=3, verbose_name='Валюта показа клиенту'),
        ),
        migrations.AddField(
            model_name='siteorder',
            name='display_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True, verbose_name='Курс показа (валюта за 1 ₩)'),
        ),
        migrations.AddField(
            model_name='siteorder',
            name='underpaid_krw',
            field=models.PositiveIntegerField(default=0, verbose_name='Не доплачено, ₩'),
        ),
        migrations.AddField(
            model_name='siteorder',
            name='underpaid_reason',
            field=models.TextField(blank=True, verbose_name='Почему оформлено без доплаты'),
        ),
        migrations.AlterField(
            model_name='siteorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплату'), ('paid', 'Оплачен'), ('manager', 'Передан консультанту'), ('consultant_draft', 'Ожидает оплату (консультант)'), ('failed', 'Ошибка оплаты'), ('cancelled', 'Отменён')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ru_employee_id', models.CharField(help_text='Владелец заказа, резерва и оплаты в Business.Ru.', max_length=32, verbose_name='ID сотрудника Business.Ru')),
                ('is_active', models.BooleanField(default=True, help_text='Выключенный консультант сразу теряет доступ к кабинету консультанта.', verbose_name='Включён')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сайта')),
            ],
            options={
                'verbose_name': 'Консультант',
                'verbose_name_plural': 'Консультанты',
                'ordering': ['user__email'],
            },
        ),
        migrations.AddField(
            model_name='siteorder',
            name='consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='market.consultant', verbose_name='Консультант'),
        ),
        migrations.CreateModel(
            name='ConsultantClientLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=254, verbose_name='Запрос')),
                ('found', models.BooleanField(default=False, verbose_name='Найден')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookups', to='market.consultant', verbose_name='Консультант')),
            ],
            options={
                'verbose_name': 'Поиск клиента',
                'verbose_name_plural': 'Поиск клиентов (журнал)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=3, verbose_name='Валюта')),
                ('rate', models.DecimalField(decimal_places=10, max_digits=18, verbose_name='Курс (валюта за 1 ₩) на момент записи')),
                ('amount_krw', models.PositiveIntegerField(verbose_name='Получено, ₩')),
                ('proof_name', models.CharField(blank=True, max_length=255, verbose_name='Файл')),
                ('proof_content_type', models.CharField(blank=True, max_length=100)),
                ('proof_data', models.BinaryField(blank=True, default=b'')),
                ('business_ru_payment_id', models.CharField(blank=True, max_length=32, verbose_name='ID оплаты Business.Ru')),
                ('business_ru_payment_number', models.CharField(blank=True, max_length=32, verbose_name='№ входящей оплаты')),
                ('business_ru_file_id', models.CharField(blank=True, max_length=32, verbose_name='ID файла Business.Ru')),
                ('business_ru_file_error', models.TextField(blank=True, verbose_name='Фото в Business.Ru не загружено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто записал')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='market.siteorder')),
            ],
            options={
                'verbose_name': 'Оплата клиента',
                'verbose_name_plural': 'Оплаты клиента',
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
